#cloud-config
write_files:
  - path: /kubeadm-config.yml
    content: |
      apiVersion: kubeadm.k8s.io/v1beta2
      caCertPath: /etc/kubernetes/pki/ca.crt
      discovery:
        bootstrapToken:
          apiServerEndpoint: <Master Instance IP>:6443
          token: <kubeadm token>
          caCertHashes:
            - "<token hash>"
        timeout: 5m0s
        tlsBootstrapToken: <kubeadm token>
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: "external"

runcmd:
- kubeadm join --config /kubeadm-config.yml

