#!/bin/bash

set -euo pipefail
cd "$(dirname "$(readlink -e "${0}")")"

export KUBECONFIG="./terraform-${TARGET_CLUSTER}/ccm.kubeconfig"

# Credentials: initial credential file (test case: credential file reloading)
umask 077 && cat > api-creds.init <<EOF
{
	"name": "test",
	"api_key": "$EXOSCALE_API_KEY",
	"api_secret": "$EXOSCALE_API_SECRET"
}
EOF
ln -sf api-creds.init api-creds

# Credentials: unset variables to force grabing them from credential file
(
	unset EXOSCALE_API_SECRET
	unset EXOSCALE_API_KEY
	source "lib/ccm-helpers.bash"
	exoscale_ccm_start
)