#!/usr/bin/env bash
set -e
SCRIPT="${0##*/}"
SCRIPT_DIR="$(dirname "$(realpath -e "${0}")")"
if [ "${SCRIPT_DIR}" != "$(realpath .)" ]; then
  echo "ERROR[${SCRIPT}]: Please run this command from the repository root (directory)" >&2
  exit 1
fi


## Lint/reformat

# Terraform
echo "INFO[${SCRIPT}]: Linting/reformatting Terraform resources (*.tf)"
terraform fmt -recursive './terraform'

# YAML
echo "INFO[${SCRIPT}]: Linting YAML resources (*.yaml)"
yamllint -c './.yamllint' .

# Python
echo "INFO[${SCRIPT}]: Linting/reformatting Python resources (*.py)"
black .
flake8 --config './.flake8'
