kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  annotations:
    service.beta.kubernetes.io/exoscale-loadbalancer-zone: "de-fra-1"
    service.beta.kubernetes.io/exoscale-loadbalancer-service-instancepool-id: "$INSTANCEPOOL_ID"
    service.beta.kubernetes.io/exoscale-loadbalancer-name: "lb-ccm"
    service.beta.kubernetes.io/exoscale-loadbalancer-service-name: "lb-ccm-service"
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - name: service
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginxdemos/hello:latest
        ports:
        - containerPort: 80
