kind: Service
apiVersion: v1
metadata:
  name: nginx
  annotations:
    service.beta.kubernetes.io/exoscale-loadbalancer-zone: "de-muc-1"
    service.beta.kubernetes.io/exoscale-loadbalancer-name: "k8s-services"
    service.beta.kubernetes.io/exoscale-loadbalancer-description: "This load balancer exposes Kubernetes Services"
    service.beta.kubernetes.io/exoscale-loadbalancer-service-name: "k8s-svc-nginx"
    service.beta.kubernetes.io/exoscale-loadbalancer-service-description: "This service exposes a demo Nginx web server page"
    service.beta.kubernetes.io/exoscale-loadbalancer-service-instancepool-id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    service.beta.kubernetes.io/exoscale-loadbalancer-service-strategy: "round-robin"
    service.beta.kubernetes.io/exoscale-loadbalancer-service-healthcheck-mode: "http"
    service.beta.kubernetes.io/exoscale-loadbalancer-service-healthcheck-uri: "/"
    service.beta.kubernetes.io/exoscale-loadbalancer-service-healthcheck-interval: "10s"
    service.beta.kubernetes.io/exoscale-loadbalancer-service-healthcheck-timeout: "3s"
    service.beta.kubernetes.io/exoscale-loadbalancer-service-healthcheck-retries: "1"
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginxdemos/hello:latest
        ports:
        - containerPort: 80

