---
apiVersion: v1
kind: Secret
metadata:
  name: exoscale-credential
  namespace: kube-system
type: Opaque
data:
  api-endpoint: '$(echo -n $EXOSCALE_COMPUTE_ENDPOINT | base64)'
  api-key: '$(echo -n $EXOSCALE_API_KEY | base64)'
  api-secret: '$(echo -n $EXOSCALE_SECRET_KEY | base64)'
