---
apiVersion: v1
kind: Secret
metadata:
  name: exoscale-credential
  namespace: kube-system
type: Opaque
data:
  api-endpoint: '$(echo -n https://api.exoscale.com/v1 | base64)'
  api-key: '$(echo -n KEYXXXX | base64)'
  api-secret: '$(echo -n SECRETXXX | base64)'
---